### ISSUE TITLE
Search by Project number or WUP Number

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#2]

**Comment by SarahNWF** [comment]
Reconcile searching by project number or WUP number- right now it's difficult to search when these numbers include dashes, look into maybe making it a text field if it doesn't break anything.

**Comment by SarahNWF** [comment]
We can either add an attribute for sequence number or we can create a text column to combine the project number and sequence number to include a dash. If most projects have a project number and sequence number and staff would like to search based on both of those consistently we should combine them into one text column for them. We can copy data from the old project number column and paste in the new, leave it to the WUP staff to populate the sequence number. If most projects don't have a sequence number and staff won't need it for most projects we can keep the sequence number contained to its own integer column

**Comment by john-beamish** [comment]
> Reconcile searching by project number or WUP number- right now it's difficult to search when these numbers include dashes, look into maybe making it a text field if it doesn't break anything.

I'm having trouble finding exactly which layers/fields hold the project number and WUP number?  I'm the one who wrote down the note about this in the meeting originally and I still have no idea what I'm supposed to be fixing lol.

I'll ask about this at the next WUP meeting and see if it jogs anybody's memory.

**Comment by john-beamish** [comment]
It seems the actual issue is that some users want to search for parcel numbers without dashes, but in our database the parcel numbers have dashes, so they don't show up unless you remove the dashes in the search.

The field is already a text field, I don't know how to remove the dashes from the parcel number without writing an arcpy script that would be really tricky because of inconsistencies in the data.

If the whole point of the parcel number field is _only_ for users to copy/paste parcel numbers to pull up a parcel and they don't need to be easily readable with the dashes, then it might be worth looking into.  

IMO users can probably live with having to take an extra few seconds to manually remove the dashes, removing them seems like a pretty big project.
