### ISSUE TITLE
Parcel Label Visibility

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Wells#3]
With the parcel label visibility, do the thing where they aren't visible further out but also it seemed like most users wanted the default of the labeling to be off (users still have option to toggle back on)

**Comment by john-beamish** [comment]
I changed the parcel label visibility in the  WUP Site Desktop Map so that labels aren't visible as further out as they were before.  (This seems to be the place label visibility is set, since labels are off be default in the Parcels service)

However, in Web AppBuilder it seems that labels can be toggled off if they are defaulted to be on, but cannot be toggled on if they are defaulted to be off.  This seems to be because when you turn off labels in the web map, you're actually unchecking the "label features" box, once you do this there are no labels that exist to toggle on in Web AppBuilder.

The most promising option looks like creating a custom widget in Web AppBuilder Developer Edition.  

I'll put this issue to the side for now and come back to it once we complete some less difficult ones.

**Comment by SarahNWF** [comment]
You could create a copy of the layer in the web map's table of contents, set nothing for the symbology and toggle labels on (call the layer Parcel Labels). That way labels can be toggled on and off in the layer list in the web app. To them it will look like they're toggling labels instead of a whole layer. If you do this, make sure the label layer doesn't have pop-ups.

You're more than welcome to look into creating a widget though if you'd like. The above is just a quick solution I've done in the past.

**Comment by john-beamish** [comment]
> You could create a copy of the layer in the web map's table of contents, set nothing for the symbology and toggle labels on (call the layer Parcel Labels). That way labels can be toggled on and off in the layer list in the web app. To them it will look like they're toggling labels instead of a whole layer. If you do this, make sure the label layer doesn't have pop-ups.
> 
> You're more than welcome to look into creating a widget though if you'd like. The above is just a quick solution I've done in the past.

Thank you, that worked!  That was actually one of the solutions ChatGPT suggested when I asked but for some reason having a separate layer just for labels sounded dumb at the time even though it works perfectly.

I guess the suggestion had to come from a human lol
